/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulo_Finanzas;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USUARIO
 */
public class Crear_Cuentas extends javax.swing.JFrame {
    Connection base;
    private TableRowSorter filtro;
    /**
     * Creates new form Crear_Cuentas
     */
    public Crear_Cuentas() {
        initComponents();
    }
    /**
     * Creates new form Crear_Cuentas
     */
    public Crear_Cuentas(Connection base) {
        try {
            initComponents();
            this.base = base;
            tipo.add(Bt_activo);
            tipo.add(Bt_pasivo);
            tipo.add(Bt_Ganancia);
            tipo.add(Bt_perdida);
            Corriente.add(Bt_corriente);
            Corriente.add(Bt_nocorriente);
            Bt_activo.setSelected(true);
            Bt_corriente.setSelected(true);
            Statement b = base.createStatement();
            ResultSet consulta = b.executeQuery("SELECT cuentas.Activo,cuentas.Pasivo,cuentas.Perdida,cuentas.Ganancia,cuentas.Corriente,cuentas.Patrimonio, cuentas.Nombre FROM cuentas");
            DefaultTableModel tabla = (DefaultTableModel) cuentas.getModel();
           
            String[] agregar = new String[2];
            while(consulta.next()){
                String tipo = "";
                if(consulta.getBoolean(1)){
                    if(consulta.getBoolean(5) ){
                        tipo = "Activo(Corriente)";
                    }else{
                        tipo = "Activo(No corriente)";
                    }
                }else if(consulta.getBoolean(2)){
                    if(consulta.getBoolean(5) ){
                        tipo = "Pasivo(Corriente)";
                    }else{
                        tipo = "Pasivo(No Corriente)";
                    }
                }else if(consulta.getBoolean(3)){
                    tipo = "Perdida";
                }else if(consulta.getBoolean(4)){
                    tipo = "Ganancia";
                }else if(consulta.getBoolean(6)){
                    tipo = "Patrimonio";
                }
                
                agregar[0] = consulta.getString(7);
                agregar[1] = tipo;
                tabla.addRow(agregar);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Crear_Cuentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo = new javax.swing.ButtonGroup();
        Corriente = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cadena = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuentas = new javax.swing.JTable();
        Bt_activo = new javax.swing.JRadioButton();
        Bt_pasivo = new javax.swing.JRadioButton();
        Bt_perdida = new javax.swing.JRadioButton();
        Bt_Ganancia = new javax.swing.JRadioButton();
        Bt_corriente = new javax.swing.JRadioButton();
        Bt_nocorriente = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre :");

        cadena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cadenaKeyTyped(evt);
            }
        });

        cuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cuentas);
        if (cuentas.getColumnModel().getColumnCount() > 0) {
            cuentas.getColumnModel().getColumn(0).setResizable(false);
            cuentas.getColumnModel().getColumn(0).setPreferredWidth(200);
            cuentas.getColumnModel().getColumn(1).setResizable(false);
        }

        Bt_activo.setText("Activo");
        Bt_activo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Bt_activoItemStateChanged(evt);
            }
        });

        Bt_pasivo.setText("Pasivo");
        Bt_pasivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Bt_pasivoItemStateChanged(evt);
            }
        });

        Bt_perdida.setText("Perdida");
        Bt_perdida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Bt_perdidaItemStateChanged(evt);
            }
        });

        Bt_Ganancia.setText("Ganancia");
        Bt_Ganancia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Bt_GananciaItemStateChanged(evt);
            }
        });

        Bt_corriente.setText("Corriente");
        Bt_corriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_corrienteActionPerformed(evt);
            }
        });

        Bt_nocorriente.setText("No Corriente");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadena)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt_activo)
                            .addComponent(Bt_pasivo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt_perdida)
                            .addComponent(Bt_Ganancia))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt_corriente)
                            .addComponent(Bt_nocorriente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bt_activo)
                            .addComponent(Bt_perdida)
                            .addComponent(Bt_corriente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bt_pasivo)
                            .addComponent(Bt_Ganancia)
                            .addComponent(Bt_nocorriente)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_corrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_corrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_corrienteActionPerformed

    private void Bt_activoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Bt_activoItemStateChanged
        if(evt.getStateChange()== ItemEvent.SELECTED){
            Bt_corriente.setVisible(true);
            Bt_nocorriente.setVisible(true);
        }
    }//GEN-LAST:event_Bt_activoItemStateChanged

    private void Bt_pasivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Bt_pasivoItemStateChanged
        if(evt.getStateChange()== ItemEvent.SELECTED){
            Bt_corriente.setVisible(true);
            Bt_nocorriente.setVisible(true);
        }
    }//GEN-LAST:event_Bt_pasivoItemStateChanged

    private void Bt_perdidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Bt_perdidaItemStateChanged
        if(evt.getStateChange()== ItemEvent.SELECTED){
            Bt_corriente.setVisible(false);
            Bt_nocorriente.setVisible(false);
        }
    }//GEN-LAST:event_Bt_perdidaItemStateChanged

    private void Bt_GananciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Bt_GananciaItemStateChanged
        if(evt.getStateChange()== ItemEvent.SELECTED){
            Bt_corriente.setVisible(false);
            Bt_nocorriente.setVisible(false);
        }
    }//GEN-LAST:event_Bt_GananciaItemStateChanged

    private void cadenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadenaKeyTyped
        filtro.setRowFilter(RowFilter.regexFilter(cadena.getText(), 0));
        cuentas.setRowSorter(filtro);
    }//GEN-LAST:event_cadenaKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cantidad = cuentas.getRowCount();
        if(cantidad == 0){
            
        }else{
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Cuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bt_Ganancia;
    private javax.swing.JRadioButton Bt_activo;
    private javax.swing.JRadioButton Bt_corriente;
    private javax.swing.JRadioButton Bt_nocorriente;
    private javax.swing.JRadioButton Bt_pasivo;
    private javax.swing.JRadioButton Bt_perdida;
    private javax.swing.ButtonGroup Corriente;
    private javax.swing.JTextField cadena;
    private javax.swing.JTable cuentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup tipo;
    // End of variables declaration//GEN-END:variables
}
