/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulo_Finanzas;

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Wilson Xicará
 */
public class SeleccionarCuenta extends javax.swing.JDialog {
    private DefaultTableModel modelCuentas;
    private int indexSeleccionado;
    private TableRowSorter filtroTabla;
    /**
     * Creates new form SeleccionarCuenta
     */
    public SeleccionarCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public SeleccionarCuenta(java.awt.Frame parent, boolean modal, ArrayList<Integer> listaIDCuentas, ArrayList<String> listaNombreCuentas) {
        super(parent, modal);
        initComponents();
        // Muestro todas las cuentas en la Tabla de cuentas
        modelCuentas = (DefaultTableModel)tabla_cuentas.getModel();
        int cantidad = listaIDCuentas.size();
        for(int i=0; i<cantidad; i++)
            modelCuentas.addRow(new String[]{""+(i+1), listaNombreCuentas.get(i)});
        indexSeleccionado = -1; // Indicador de que no se ha seleccionado una cuenta
        filtroTabla = new TableRowSorter(tabla_cuentas.getModel()); // Objeto que permite filtrar cuentas de la Tabla
        tabla_cuentas.setShowHorizontalLines(true);    // Para mostrar las lineas de la tabla
        tabla_cuentas.setShowVerticalLines(true);
        this.setLocationRelativeTo(null);   // Para centrar esta ventana sobre la pantalla
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_cuentas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        nombre_cuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cuentas Contables");

        jLabel1.setText("Dar doble clic sobre la Cuenta para seleccionarla");

        tabla_cuentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla_cuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_cuentas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla_cuentas.setRowHeight(25);
        tabla_cuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_cuentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_cuentas);
        if (tabla_cuentas.getColumnModel().getColumnCount() > 0) {
            tabla_cuentas.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabla_cuentas.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        jLabel2.setText("Buscar Cuenta:");

        nombre_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombre_cuentaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_cuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_cuentasMouseClicked
        if (evt.getClickCount() == 2) { // Compruebo que haya seleccioado doble clic
            indexSeleccionado = filtroTabla.convertRowIndexToModel(tabla_cuentas.getSelectedRow());
            this.dispose(); // Cierro el JDialog
        }
    }//GEN-LAST:event_tabla_cuentasMouseClicked

    private void nombre_cuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_cuentaKeyPressed
        filtroTabla.setRowFilter(RowFilter.regexFilter(nombre_cuenta.getText(), 1));
        tabla_cuentas.setRowSorter(filtroTabla);
    }//GEN-LAST:event_nombre_cuentaKeyPressed

    public int getIndexSeleccionado() { return indexSeleccionado; }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionarCuenta dialog = new SeleccionarCuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre_cuenta;
    private javax.swing.JTable tabla_cuentas;
    // End of variables declaration//GEN-END:variables
}
